<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV9hbwsR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV9hbwsR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV9hbwsR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV9hbwsR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV9hbwsR\App_KernelDevDebugContainer([
    'container.build_hash' => 'V9hbwsR',
    'container.build_id' => 'd05394c6',
    'container.build_time' => 1706999022,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV9hbwsR');
